language: cpp
dist:
    - trusty
    - xenial
compiler:
    - clang
os:
    - linux
addons:
    apt:
        packages:
            - cmake
            - qtbase5-dev

script:
    - mkdir b && cd b && cmake -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build .
    - ./squco-test
